#!/bin/bash
DOMAIN=${1:-topvalue.local}
VERSION=${2:-2.3.3}

curl -s https://raw.githubusercontent.com/topvalue/m2_docker/master/lib/template?token=AB5MMZ6SL3FLJXBEAGH4QLK5VSIHQ|bash -s - magento-2
bin/download $VERSION

echo "Your system password has been requested to add an entry to /etc/hosts..."
echo "127.0.0.1 $DOMAIN" | sudo tee -a /etc/hosts

bin/setup $DOMAIN
